# Setup
title:        Kellie Carlson
tagline:      Computer Science Student
baseurl:      "carlsonkellie.github.io"
paginate:     1

# About/contact
author:       Kellie Carlson
  name:       Kellie Carlson
  url:        http://carlsonkellie.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
