# Setup
title:        Kellie Carlson
tagline:      Candidate for BSE in Computer Science, University of Pennsylvania
baseurl:      ""
paginate:     1
blog_title:   Under Pressure
blog_tagline: Recipes for College Students by a College Student!

# About/contact
author:
  name:       Kellie Carlson
  url:        https://github.com/carlsonkellie

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
future: true
