# Setup
title:        Kellie Carlson
tagline:      Computer Science Student
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Kellie Carlson
  url:        https://github.com/carlsonkellie

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
future: true
