# Setup
title:        Kellie Carlson
tagline:      Computer Science Student!
baseurl:      ""
paginate:     1

# About/contact
author:       Kellie Carlson
  name:       Kellie Carlson
  url:        carlsonkellie.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
future: true
